# Generated by Django 5.1 on 2024-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='is_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
