# Generated by Django 5.1 on 2024-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_change_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
