# Generated by Django 5.1 on 2024-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_userprofile_password_change_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
