# Generated by Django 5.1 on 2024-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_loginsettings_remove_userprofile_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='is_locked_out',
            field=models.BooleanField(default=False),
        ),
    ]
